spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

# Properties for zipkin if default values are not used
#management:
#  zipkin:
#    tracing:
#      endpoint:


